[build]
  functions = "functions"

[[redirects]]
from = "/myfunc"
to = "/.netlify/functions/myfunc"
status = 200
force = true 

[[redirects]]
from = "/myotherfunc"
to = "/.netlify/functions/myotherfunc"
status = 200
force = true 